# Config taken from https://stackoverflow.com/a/77257732
#
# This docker-compose is for development and test purposes. Tests are recorded with
# VCR against this instance.
#
#   Log in to http://localhost:8080/admin/master/console/ with `admin`/`admin`
#   credentials.
#
# DO NOT USE THIS IN PRODUCTION.
#

version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./docker/import:/opt/keycloak/data/import
    ports:
      - 8080:8080
