# Generated by Django 4.2.15 on 2024-09-17 08:20

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid
import vng_api_common.fields
import vng_api_common.models


class Migration(migrations.Migration):

    dependencies = [
        ("vng_api_common", "0005_auto_20190614_1346"),
    ]

    operations = [
        migrations.CreateModel(
            name="Applicatie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unique resource identifier (UUID4)",
                        unique=True,
                    ),
                ),
                (
                    "client_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        help_text="Komma-gescheiden lijst van consumer identifiers (hun client_id).",
                        size=None,
                        verbose_name="client IDs",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Een leesbare representatie van de applicatie, voor eindgebruikers.",
                        max_length=100,
                    ),
                ),
                (
                    "heeft_alle_autorisaties",
                    models.BooleanField(
                        default=False,
                        help_text="Indien alle autorisaties gegeven zijn, dan hoeven deze niet individueel opgegeven te worden. Gebruik dit alleen als je de consumer helemaal vertrouwt.",
                        verbose_name="heeft alle autorisaties",
                    ),
                ),
            ],
            bases=(vng_api_common.models.APIMixin, models.Model),
        ),
        migrations.CreateModel(
            name="AuthorizationsConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_root",
                    models.URLField(
                        default="https://autorisaties-api.vng.cloud/api/v1",
                        unique=True,
                        verbose_name="api root",
                    ),
                ),
                (
                    "component",
                    models.CharField(
                        choices=[
                            ("ac", "Autorisaties API"),
                            ("nrc", "Notificaties API"),
                            ("zrc", "Zaken API"),
                            ("ztc", "Catalogi API"),
                            ("drc", "Documenten API"),
                            ("brc", "Besluiten API"),
                            ("cmc", "Contactmomenten API"),
                            ("kc", "Klanten API"),
                            ("vrc", "Verzoeken API"),
                        ],
                        default="zrc",
                        max_length=50,
                        verbose_name="component",
                    ),
                ),
            ],
            options={
                "verbose_name": "Autorisatiecomponentconfiguratie",
            },
        ),
        migrations.CreateModel(
            name="Autorisatie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "component",
                    models.CharField(
                        choices=[
                            ("ac", "Autorisaties API"),
                            ("nrc", "Notificaties API"),
                            ("zrc", "Zaken API"),
                            ("ztc", "Catalogi API"),
                            ("drc", "Documenten API"),
                            ("brc", "Besluiten API"),
                            ("cmc", "Contactmomenten API"),
                            ("kc", "Klanten API"),
                            ("vrc", "Verzoeken API"),
                        ],
                        help_text="Component waarop autorisatie van toepassing is.",
                        max_length=50,
                        verbose_name="component",
                    ),
                ),
                (
                    "scopes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        help_text="Komma-gescheiden lijst van scope labels.",
                        size=None,
                        verbose_name="scopes",
                    ),
                ),
                (
                    "zaaktype",
                    models.URLField(
                        blank=True,
                        help_text="URL naar het zaaktype waarop de autorisatie van toepassing is.",
                        max_length=1000,
                        verbose_name="zaaktype",
                    ),
                ),
                (
                    "informatieobjecttype",
                    models.URLField(
                        blank=True,
                        help_text="URL naar het informatieobjecttype waarop de autorisatie van toepassing is.",
                        max_length=1000,
                        verbose_name="informatieobjecttype",
                    ),
                ),
                (
                    "besluittype",
                    models.URLField(
                        blank=True,
                        help_text="URL naar het besluittype waarop de autorisatie van toepassing is.",
                        max_length=1000,
                        verbose_name="besluittype",
                    ),
                ),
                (
                    "max_vertrouwelijkheidaanduiding",
                    vng_api_common.fields.VertrouwelijkheidsAanduidingField(
                        blank=True,
                        choices=[
                            ("openbaar", "Openbaar"),
                            ("beperkt_openbaar", "Beperkt openbaar"),
                            ("intern", "Intern"),
                            ("zaakvertrouwelijk", "Zaakvertrouwelijk"),
                            ("vertrouwelijk", "Vertrouwelijk"),
                            ("confidentieel", "Confidentieel"),
                            ("geheim", "Geheim"),
                            ("zeer_geheim", "Zeer geheim"),
                        ],
                        help_text="Maximaal toegelaten vertrouwelijkheidaanduiding (inclusief).",
                        max_length=20,
                    ),
                ),
                (
                    "applicatie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="autorisaties",
                        to="vng_api_common.applicatie",
                        verbose_name="applicatie",
                    ),
                ),
            ],
            bases=(vng_api_common.models.APIMixin, models.Model),
        ),
    ]
