# Generated by Django 5.1.7 on 2025-04-15 07:26

import vng_api_common.fields
from django.db import migrations
from vng_api_common.constants import VA_MAPPING, REVERSE_VA_MAPPING


def populate_max_vertrouwelijkheidaanduiding_integer_field(apps, schema_editor):
    Autorisatie = apps.get_model("authorizations", "Autorisatie")
    BATCH_SIZE = 2000
    batch = []
    for instance in Autorisatie.objects.iterator():
        if not (max_va := VA_MAPPING.get(instance.max_vertrouwelijkheidaanduiding)):
            continue

        instance._max_vertrouwelijkheidaanduiding = max_va
        batch.append(instance)

        if len(batch) >= BATCH_SIZE:
            Autorisatie.objects.bulk_update(batch, ["_max_vertrouwelijkheidaanduiding"])
            batch.clear()

    # Handle final batch
    if batch:
        Autorisatie.objects.bulk_update(batch, ["_max_vertrouwelijkheidaanduiding"])


def populate_max_vertrouwelijkheidaanduiding_char_field(apps, schema_editor):
    Autorisatie = apps.get_model("authorizations", "Autorisatie")
    BATCH_SIZE = 2000
    batch = []
    for instance in Autorisatie.objects.filter(
        max_vertrouwelijkheidaanduiding=""
    ).iterator():
        if not (
            max_va := REVERSE_VA_MAPPING.get(instance._max_vertrouwelijkheidaanduiding)
        ):
            continue

        instance.max_vertrouwelijkheidaanduiding = max_va
        batch.append(instance)

        if len(batch) >= BATCH_SIZE:
            Autorisatie.objects.bulk_update(batch, ["max_vertrouwelijkheidaanduiding"])
            batch.clear()

    # Handle final batch
    if batch:
        Autorisatie.objects.bulk_update(batch, ["max_vertrouwelijkheidaanduiding"])


class Migration(migrations.Migration):

    dependencies = [
        ("authorizations", "0017_alter_applicatie_client_ids_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="autorisatie",
            name="_max_vertrouwelijkheidaanduiding",
            field=vng_api_common.fields.VertrouwelijkheidsAanduidingFieldInt(
                blank=True,
                choices=[
                    (10, "Openbaar"),
                    (20, "Beperkt openbaar"),
                    (30, "Intern"),
                    (40, "Zaakvertrouwelijk"),
                    (50, "Vertrouwelijk"),
                    (60, "Confidentieel"),
                    (70, "Geheim"),
                    (80, "Zeer geheim"),
                ],
                db_index=True,
                help_text="Maximaal toegelaten vertrouwelijkheidaanduiding (inclusief).",
                null=True,
            ),
        ),
        migrations.RunPython(
            populate_max_vertrouwelijkheidaanduiding_integer_field,
            populate_max_vertrouwelijkheidaanduiding_char_field,
        ),
    ]
