# Generated by Django 4.2.19 on 2025-03-25 10:44

from django.db import migrations
from vng_api_common.constants import MAPPING


def forward(apps, schema_editor):
    Autorisatie = apps.get_model("authorizations", "Autorisatie")
    for autorisatie in Autorisatie.objects.iterator():
        autorisatie.max_vertrouwelijkheidaanduiding = MAPPING[autorisatie.max_vertrouwelijkheidaanduiding]
        autorisatie.save(update_fields=["max_vertrouwelijkheidaanduiding"])


class Migration(migrations.Migration):

    dependencies = [
        ("authorizations", "0018_alter_autorisatie_max_vertrouwelijkheidaanduiding"),
    ]

    operations = [migrations.RunPython(forward, migrations.RunPython.noop)]
