# Generated by Django 5.2.3 on 2025-07-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0009_geometrymodel_mediafilemodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fkmodel",
            name="name",
            field=models.CharField(
                help_text="FkModel simple name help_text",
                max_length=100,
                verbose_name="name",
            ),
        ),
    ]
