# Generated by Django 5.2.3 on 2025-07-08 10:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0010_alter_fkmodel_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notitie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke identificatie door notitie",
                        unique=True,
                    ),
                ),
                (
                    "onderwerp",
                    models.CharField(
                        blank=True,
                        help_text="Korte omschrijving of titel van de notitie",
                        max_length=255,
                    ),
                ),
                (
                    "tekst",
                    models.TextField(
                        blank=True,
                        help_text="De volledige inhoud of beschrijving van de notitie",
                    ),
                ),
                (
                    "aangemaakt_door",
                    models.CharField(
                        blank=True,
                        help_text="Naam of identificatie van de auteur van de notitie",
                        max_length=255,
                    ),
                ),
                (
                    "notitie_type",
                    models.CharField(
                        choices=[("intern", "Intern"), ("extern", "Extern")],
                        default="intern",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("concept", "Concept"), ("definitief", "Definitief")],
                        default="concept",
                        max_length=50,
                    ),
                ),
                (
                    "aanmaakdatum",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="De datum waarop de handeling is gedaan.",
                    ),
                ),
                (
                    "wijzigingsdatum",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Datum en tijd waarop de notitie voor het laatst is gewijzigd",
                    ),
                ),
                (
                    "gerelateerd_aan",
                    models.URLField(
                        blank=True,
                        help_text="URL van het gerelateerde object",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "notitie",
                "verbose_name_plural": "notities",
            },
        ),
    ]
