# Generated by Django 5.2.3 on 2025-10-01 09:41

import vng_api_common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_notitie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medewerker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bsn', vng_api_common.fields.BSNField(blank=True, max_length=9, null=True)),
                ('rsin', vng_api_common.fields.RSINField(blank=True, max_length=9, null=True)),
            ],
        ),
    ]
