# Generated by Django 4.2.18 on 2025-10-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0012_medewerker"),
    ]

    operations = [
        migrations.AddField(
            model_name="fkmodel",
            name="attribute1",
            field=models.CharField(
                blank=True,
                help_text="charfield",
                max_length=100,
                verbose_name="attribute1",
            ),
        ),
        migrations.AddField(
            model_name="fkmodel",
            name="attribute2",
            field=models.CharField(
                blank=True,
                choices=[("op1", "Option 1"), ("op2", "Option 2")],
                help_text="choicefield",
                verbose_name="attribute2",
            ),
        ),
    ]
